title: Iqbwl Archive
subtitle: Personal Blogs
author: iqbwl
email: iqbwl@abc.web.id
description: > # description of the site (multiple lines allowed)
  personal blogs

url: "https://iqbwl.github.io"
permalink: /:slug

favicon: "/favicon.ico"

remote_theme: iqbwl/another-minima-x

# Front matter defaults
defaults:
  # Posts defaults
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "iqbwl"
      categories: ["uncategorized"]
      comments: false
  # Pages defaults
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      author: "iqbwl"

header_pages:
  - title: More
    children:
      - title: Docs
        url: /docs/
      - title: Learning
        url: /learning/

# SCSS compilation settings
sass:
  quiet_deps: true
  silence_deprecations:
    - import
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Files and folders to exclude from build
exclude:
  - .gitignore
  - .git/
  - .jekyll-cache/
  - .sass-cache/
  - README.md
  - Gemfile
  - Gemfile.lock
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.txt

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

include:
  - svg
  - img
  - migrated
